# Generated by Django 3.0.7 on 2020-06-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200616_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='face_pic',
            field=models.ImageField(blank=True, help_text='For students, please upload a photo showing your face.\n        This will be used to record your attendance through facial recognition.', null=True, upload_to='', verbose_name='Choose Profile Picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_instructor',
            field=models.BooleanField(default=False, help_text='Please check this field only if you are a course instructor.\n        For students, please leave this unchecked.', verbose_name='I am a Course Instructor'),
        ),
    ]
