# Generated by Django 3.0.7 on 2020-06-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20200611_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AlterField(
            model_name='enrollement',
            name='date_enrolled',
            field=models.DateField(verbose_name='Date Enrolled'),
        ),
    ]
