# Generated by Django 3.0.7 on 2020-06-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20200611_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='enrollement',
            options={'verbose_name': 'Enrollement', 'verbose_name_plural': 'Enrollement'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterField(
            model_name='enrollement',
            name='date_enrolled',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Enrolled'),
        ),
    ]
