# Generated by Django 3.0.7 on 2020-06-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20200614_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255, unique=True, verbose_name='Course Slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Course Name'),
        ),
    ]
