# Generated by Django 3.0.7 on 2020-06-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20200615_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollement',
            name='student',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Enrollement',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
