# Generated by Django 3.0.7 on 2020-06-15 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0010_auto_20200615_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
