# Generated by Django 3.0.7 on 2020-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_lesson_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_date',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lesson Date'),
        ),
    ]
