# Generated by Django 3.0.7 on 2020-06-16 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_auto_20200616_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='attendance.Lesson'),
            preserve_default=False,
        ),
    ]
