# Generated by Django 3.0.7 on 2020-06-18 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0018_auto_20200617_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_enrolment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='students',
            field=models.ManyToManyField(through='attendance.Proof', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='attendance.Course'),
        ),
    ]
