# Generated by Django 3.0.7 on 2020-06-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_remove_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolment',
            name='final_grade',
        ),
    ]
