# Generated by Django 3.0.7 on 2020-06-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_remove_enrolment_final_grade'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance',
            table='attendance',
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='enrolment',
            table='enrolment',
        ),
        migrations.AlterModelTable(
            name='proof',
            table='attendance_proof',
        ),
    ]
